import { GitService } from '../../../core/git/git-service';
import { ProjectConfig, Framework, Language, PackageManager, TemplateType } from '../../../types';
import * as fs from 'fs-extra';
import * as path from 'path';
import { execSync } from 'child_process';

describe('GitService', () => {
  let gitService: GitService;
  let testProjectPath: string;
  let mockConfig: ProjectConfig;

  beforeEach(() => {
    gitService = new GitService();
    testProjectPath = path.join(__dirname, 'test-project');
    
    mockConfig = {
      projectName: 'test-project',
      framework: Framework.NEXTJS,
      template: TemplateType.MINIMAL,
      language: Language.TYPESCRIPT,
      styling: { includeTailwind: true },
      stateManagement: { includeZustand: false },
      dataFetching: { includeTanStackQuery: false },
      devTools: { includeESLint: true, includePrettier: true },
      packageManager: PackageManager.NPM,
      gitInit: true,
    };
  });

  afterEach(async () => {
    // Clean up test directory
    if (await fs.pathExists(testProjectPath)) {
      await fs.remove(testProjectPath);
    }
  });

  describe('createGitignore', () => {
    beforeEach(async () => {
      await fs.ensureDir(testProjectPath);
    });

    it('should create a .gitignore file with framework-specific content', async () => {
      const result = await gitService.createGitignore(testProjectPath, mockConfig);
      
      expect(result.success).toBe(true);
      expect(result.message).toContain('.gitignore file created successfully');
      
      const gitignorePath = path.join(testProjectPath, '.gitignore');
      expect(await fs.pathExists(gitignorePath)).toBe(true);
      
      const content = await fs.readFile(gitignorePath, 'utf-8');
      expect(content).toContain('# Generated by starter-cli');
      expect(content).toContain('node_modules/');
      expect(content).toContain('/.next/'); // Next.js specific
      expect(content).toContain('.env');
    });

    it('should include Vite-specific entries for React + Vite projects', async () => {
      const viteConfig = { ...mockConfig, framework: Framework.REACT_VITE };
      
      const result = await gitService.createGitignore(testProjectPath, viteConfig);
      
      expect(result.success).toBe(true);
      
      const gitignorePath = path.join(testProjectPath, '.gitignore');
      const content = await fs.readFile(gitignorePath, 'utf-8');
      expect(content).toContain('# Vite specific');
      expect(content).toContain('dist-ssr');
    });

    it('should include package manager specific entries', async () => {
      const yarnConfig = { ...mockConfig, packageManager: PackageManager.YARN };
      
      const result = await gitService.createGitignore(testProjectPath, yarnConfig);
      
      expect(result.success).toBe(true);
      
      const gitignorePath = path.join(testProjectPath, '.gitignore');
      const content = await fs.readFile(gitignorePath, 'utf-8');
      expect(content).toContain('# Yarn');
      expect(content).toContain('.yarn/*');
    });

    it('should merge with existing .gitignore file', async () => {
      const existingContent = '# Existing content\ncustom-file.txt\n';
      const gitignorePath = path.join(testProjectPath, '.gitignore');
      await fs.writeFile(gitignorePath, existingContent, 'utf-8');
      
      const result = await gitService.createGitignore(testProjectPath, mockConfig);
      
      expect(result.success).toBe(true);
      expect(result.message).toContain('.gitignore file updated');
      
      const content = await fs.readFile(gitignorePath, 'utf-8');
      expect(content).toContain('# Existing content');
      expect(content).toContain('custom-file.txt');
      expect(content).toContain('# Generated by starter-cli');
    });

    it('should not overwrite if already configured', async () => {
      const existingContent = '# Generated by starter-cli\nnode_modules/\n';
      const gitignorePath = path.join(testProjectPath, '.gitignore');
      await fs.writeFile(gitignorePath, existingContent, 'utf-8');
      
      const result = await gitService.createGitignore(testProjectPath, mockConfig);
      
      expect(result.success).toBe(true);
      expect(result.message).toContain('already exists and appears to be configured');
    });
  });

  describe('initializeRepository', () => {
    beforeEach(async () => {
      await fs.ensureDir(testProjectPath);
    });

    it('should handle Git not being available', async () => {
      // Mock execSync to throw an error for git --version
      const originalExecSync = execSync;
      (execSync as any) = jest.fn().mockImplementation((command: string) => {
        if (command === 'git --version') {
          throw new Error('Git not found');
        }
        return originalExecSync(command);
      });

      const result = await gitService.initializeRepository(testProjectPath);
      
      expect(result.success).toBe(false);
      expect(result.message).toContain('Git is not available');
      
      // Restore original execSync
      (execSync as any) = originalExecSync;
    });

    it('should detect existing Git repository', async () => {
      // Create a .git directory to simulate existing repo
      const gitDir = path.join(testProjectPath, '.git');
      await fs.ensureDir(gitDir);
      
      const result = await gitService.initializeRepository(testProjectPath);
      
      expect(result.success).toBe(true);
      expect(result.message).toContain('Git repository already exists');
    });

    // Note: We skip testing actual Git initialization in unit tests
    // as it requires Git to be available and would create real repositories
  });

  describe('createInitialCommit', () => {
    beforeEach(async () => {
      await fs.ensureDir(testProjectPath);
    });

    it('should handle Git not being available', async () => {
      // Mock execSync to throw an error for git --version
      const originalExecSync = execSync;
      (execSync as any) = jest.fn().mockImplementation((command: string) => {
        if (command === 'git --version') {
          throw new Error('Git not found');
        }
        return originalExecSync(command);
      });

      const result = await gitService.createInitialCommit(testProjectPath);
      
      expect(result.success).toBe(false);
      expect(result.message).toContain('Git is not available');
      
      // Restore original execSync
      (execSync as any) = originalExecSync;
    });

    it('should handle non-Git directory', async () => {
      // Mock execSync to throw an error for git status
      const originalExecSync = execSync;
      (execSync as any) = jest.fn().mockImplementation((command: string) => {
        if (command === 'git --version') {
          return 'git version 2.0.0';
        }
        if (command === 'git status --porcelain') {
          throw new Error('Not a git repository');
        }
        return originalExecSync(command);
      });

      const result = await gitService.createInitialCommit(testProjectPath);
      
      expect(result.success).toBe(false);
      expect(result.message).toContain('Not a Git repository');
      
      // Restore original execSync
      (execSync as any) = originalExecSync;
    });
  });
});