import { execSync } from 'child_process';
import * as fs from 'fs-extra';
import * as path from 'path';
import { Framework, ProjectConfig } from '../../types';

/**
 * Git service for repository initialization and configuration
 */
export class GitService {
  /**
   * Initializes a Git repository in the project directory
   */
  async initializeRepository(projectPath: string): Promise<{ success: boolean; message: string }> {
    try {
      // Check if Git is available
      if (!this.isGitAvailable()) {
        return {
          success: false,
          message: 'Git is not available on this system. Please install Git to initialize a repository.'
        };
      }

      // Check if already a Git repository
      const gitDir = path.join(projectPath, '.git');
      if (await fs.pathExists(gitDir)) {
        return {
          success: true,
          message: 'Git repository already exists in this directory.'
        };
      }

      // Initialize Git repository
      execSync('git init', { 
        cwd: projectPath, 
        stdio: 'ignore' 
      });

      return {
        success: true,
        message: 'Git repository initialized successfully.'
      };
    } catch (error) {
      return {
        success: false,
        message: `Failed to initialize Git repository: ${error instanceof Error ? error.message : 'Unknown error'}`
      };
    }
  }

  /**
   * Creates an appropriate .gitignore file for the framework
   */
  async createGitignore(projectPath: string, config: ProjectConfig): Promise<{ success: boolean; message: string }> {
    try {
      const gitignoreContent = this.generateGitignoreContent(config);
      const gitignorePath = path.join(projectPath, '.gitignore');

      // Check if .gitignore already exists
      if (await fs.pathExists(gitignorePath)) {
        // Read existing content and merge if needed
        const existingContent = await fs.readFile(gitignorePath, 'utf-8');
        if (!existingContent.includes('# Generated by starter-cli')) {
          // Append our content to existing .gitignore
          const mergedContent = existingContent.trim() + '\n\n' + gitignoreContent;
          await fs.writeFile(gitignorePath, mergedContent, 'utf-8');
          return {
            success: true,
            message: '.gitignore file updated with framework-specific entries.'
          };
        } else {
          return {
            success: true,
            message: '.gitignore file already exists and appears to be configured.'
          };
        }
      } else {
        // Create new .gitignore file
        await fs.writeFile(gitignorePath, gitignoreContent, 'utf-8');
        return {
          success: true,
          message: '.gitignore file created successfully.'
        };
      }
    } catch (error) {
      return {
        success: false,
        message: `Failed to create .gitignore file: ${error instanceof Error ? error.message : 'Unknown error'}`
      };
    }
  }

  /**
   * Performs initial commit if repository is clean
   */
  async createInitialCommit(projectPath: string): Promise<{ success: boolean; message: string }> {
    try {
      // Check if Git is available
      if (!this.isGitAvailable()) {
        return {
          success: false,
          message: 'Git is not available for creating initial commit.'
        };
      }

      // Check if there are any files to commit
      try {
        execSync('git status --porcelain', { 
          cwd: projectPath, 
          stdio: 'pipe' 
        });
      } catch (error) {
        return {
          success: false,
          message: 'Not a Git repository or no files to commit.'
        };
      }

      // Add all files
      execSync('git add .', { 
        cwd: projectPath, 
        stdio: 'ignore' 
      });

      // Create initial commit
      execSync('git commit -m "Initial commit from starter-cli"', { 
        cwd: projectPath, 
        stdio: 'ignore' 
      });

      return {
        success: true,
        message: 'Initial commit created successfully.'
      };
    } catch (error) {
      // If commit fails (e.g., no user.name/user.email configured), that's okay
      return {
        success: false,
        message: `Could not create initial commit: ${error instanceof Error ? error.message : 'Unknown error'}. You may need to configure Git user settings.`
      };
    }
  }

  /**
   * Checks if Git is available on the system
   */
  private isGitAvailable(): boolean {
    try {
      execSync('git --version', { stdio: 'ignore' });
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Generates .gitignore content based on framework and configuration
   */
  private generateGitignoreContent(config: ProjectConfig): string {
    const lines: string[] = [
      '# Generated by starter-cli',
      '',
      '# Dependencies',
      'node_modules/',
      '/.pnp',
      '.pnp.js',
      '',
      '# Testing',
      '/coverage',
      '',
      '# Production builds',
      '/build',
      '/dist',
      '',
      '# Environment variables',
      '.env',
      '.env.local',
      '.env.development.local',
      '.env.test.local',
      '.env.production.local',
      '',
      '# Logs',
      'npm-debug.log*',
      'yarn-debug.log*',
      'yarn-error.log*',
      'lerna-debug.log*',
      '',
      '# Runtime data',
      'pids',
      '*.pid',
      '*.seed',
      '*.pid.lock',
      '',
      '# Optional npm cache directory',
      '.npm',
      '',
      '# Optional eslint cache',
      '.eslintcache',
      '',
      '# IDE and editor files',
      '.vscode/',
      '.idea/',
      '*.swp',
      '*.swo',
      '*~',
      '',
      '# OS generated files',
      '.DS_Store',
      '.DS_Store?',
      '._*',
      '.Spotlight-V100',
      '.Trashes',
      'ehthumbs.db',
      'Thumbs.db',
    ];

    // Framework-specific entries
    if (config.framework === Framework.NEXTJS) {
      lines.push(
        '',
        '# Next.js specific',
        '/.next/',
        '/out/',
        'next-env.d.ts',
        '',
        '# Vercel',
        '.vercel',
        '',
        '# Turbo',
        '.turbo'
      );
    } else if (config.framework === Framework.REACT_VITE) {
      lines.push(
        '',
        '# Vite specific',
        'dist-ssr',
        '*.local',
        '',
        '# Vite build outputs',
        '/dist/',
        '/build/'
      );
    }

    // TypeScript specific
    if (config.language === 'typescript') {
      lines.push(
        '',
        '# TypeScript',
        '*.tsbuildinfo'
      );
    }

    // Package manager specific
    switch (config.packageManager) {
      case 'yarn':
        lines.push(
          '',
          '# Yarn',
          '.yarn/*',
          '!.yarn/patches',
          '!.yarn/plugins',
          '!.yarn/releases',
          '!.yarn/sdks',
          '!.yarn/versions',
          '.pnp.*'
        );
        break;
      case 'pnpm':
        lines.push(
          '',
          '# PNPM',
          '.pnpm-debug.log*'
        );
        break;
    }

    return lines.join('\n') + '\n';
  }
}